apiVersion: v1
kind: Secret
metadata:
  namespace: mousai
  name: pandoras-box
data:
  spotify-access-token: blah
  spotify-refresh-token: blah
  spotify-client-id: blah
  spotify-client-secret: blah
